### ISSUE TITLE
Validation not working on organisation details in setup

### ISSUE THREAD

**Issue by wesobi** [openknowledgebe/W4P#66] opened 2016-05-09 07:34 UTC
The set up doesn't work anymore at step 3 when following the set up. 
It does work when you use `php artisan db:seed --class=SettingsTestSeeder` though.

Notified @u-nico about this already, and told me I could assign him.

**Comment by ghost** [comment] 2016-05-09 09:48
I followed the instructions in the README, and there was no problem when filling in step 3 on my end here. What went wrong? What exception was raised?

**Comment by wesobi** [comment] 2016-05-09 11:49
Do you follow the "ez-mode" set up steps?

If you follow those you get an error at the start (as it doesn't include npm install / bower install + gulp command lines) and at the third step you get the error page and the following error in your logs
`19 NOT NULL constraint failed: settings.value (SQL: insert into "settings" ("key", "value", "updated_at", "created_at") values (organisation.vat, , 2016-05-09 11:46:06, 2016-05-09 11:46:06))`

So if I want to test it with my own installer instead of the SettingsTestSeeder that happens.

Maybe it would be best to remove the "ez-mode" part for now out of the setup.md, if the normal one does work.

**Comment by ghost** [comment] 2016-05-09 11:56
No, I follow the full steps above `ez-mode`. The `ez-mode` steps should be removed (I'm taking care of that right now) since those instructions are incomplete, as you mentioned.

There's also the script you can try in /vagrant/setup.sh, but that one needs to be checked if it works with the latest commits (it should... but I just glanced at it, so no 100% assurance there).

This particular error you're running into seems to be because the organisation VAT field is empty, and a setting stored in the DB may not be empty. 

(Did you leave the field empty? That might explain things.) The real issue here is that the validation for that field is either non-existent or invalid. I'll rename the issue.

**Comment by ghost** [comment] 2016-05-09 11:59
I've pushed a fix for the missing validation. Can you check if you can still run into the same issue? Thanks. If it's fixed, feel free to close this issue.

**Comment by wesobi** [comment] 2016-05-09 12:00
I can't leave it empty because the front-end validation works on the VAT field. Though I just entered 6 numbers (123456) as that is the minimum amount of chars you need. Maybe that was the issue then? Not being a valid VAT, though still passing through the validation by just adding 6 random numbers?

**Comment by ghost** [comment] 2016-05-09 12:07
So the validation wasn't broken in the first place?

The VAT number can be any string, for flexibility. The insert that failed above seems to indicate that the VAT field was left empty. I'll run through the wizard again to see if I can reproduce it.

**Comment by ghost** [comment] 2016-05-09 12:13
Oh I misunderstood -- it's actually the fourth step (with /3 in the URL) that gives an error. Can you pull and verify that this issue is fixed?

**Comment by wesobi** [comment] 2016-05-09 12:20
It works now, sweet. :) 👍

**Closed as completed** 2016-05-09 12:21 UTC
Labels: bug
